### ISSUE TITLE
putting JS code in url query param - security risk

### ISSUE THREAD

**Issue by darrinmn9** [reaalkhalil/JSRobot#5]
if you go to https://lab.reaal.me/jsrobot/#level=1, then press the restart button the url becomes `https://lab.reaal.me/jsrobot/#level=1&code=function init(robot){%0A  // your code here%0A}%0A%0Afunction loop(robot){%0A  // your code here%0A}%0A`, you shouldnt be taking a string from a query parameter and parsing it into JS that a user can execute but clicking `apply` on the script page.

`https://lab.reaal.me/jsrobot/#level=1&code=function init(robot){%0A  alert('attack')%0A}%0A%0Afunction loop(robot){%0A  // your code here%0A}%0A` i could send this to someone and inject JS into their page when they press apply. Yes, it may take a stupid person to not realize this before clicking the apply button, but its better to assume all users are stupid. This should be fixed.

**Comment by qgustavor** [comment]
@darrinmn9 [Hey, check this solution I found!](https://codepen.io/anon/pen/boPraj "In other words, just make it work like any other website which accepts user provided code: load it in a sub-domain where cookies and other important data aren't used and cannot be acessed.")

**Comment by moosbruggerj** [comment]
A possibility may be to store the JS code in the localstorage. afaik it is not possible to inject malicious code there, if the site is not already compromised. Apart from that the progress of a level can be saved for later continuation, if someone doesn't want to do it all at once.

**Comment by reaalkhalil** [comment]
@moosbruggerj actually yeah localStorage is a good idea, will do that

**Comment by reaalkhalil** [comment]
fixed with commit caf296f
